preset: recommended

risky: true

enabled:
  - long_array_syntax
  - pre_increment

disabled:
  - short_array_syntax
  - align_double_arrow
  - align_phpdoc
  - post_increment

finder:
  exclude:
    - "test"
  name:
    - "*.php"
