sudo: false

language: php
dist: precise

env:
  - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  - GET_COVERAGE=yes
  - GET_COVERAGE=no

matrix:
  include:
    - php: hhvm
      dist: trusty
      env:
        - GET_COVERAGE=no
  exclude:
    - php: 5.3
      env: GET_COVERAGE=yes
    - php: 5.4
      env: GET_COVERAGE=yes
    - php: 5.5
      env: GET_COVERAGE=yes
    - php: 5.6
      env: GET_COVERAGE=yes
    - php: 7.0
      env: GET_COVERAGE=yes
    - php: 7.1
      env: GET_COVERAGE=no
    - php: hhvm
      env: GET_COVERAGE=yes
    - php: nightly
      env: GET_COVERAGE=yes
  allow_failures:
    - php: nightly

before_script:
  - mv -f -v composer-travis-ci-coverage-$GET_COVERAGE.json composer.json
  - composer self-update
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - if [[ "$GET_COVERAGE" == "yes" ]]; then ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else ./vendor/bin/phpunit; fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

after_script:
  - if [[ "$GET_COVERAGE" == "yes" ]]; then php vendor/bin/coveralls -v && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

notifications:
  email: false
