sudo: false

language: php

notifications:
  email: false

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.composer/cache

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.2
- 7.3
- hhvm
- nightly

env:
  global:
  - GET_COVERAGE=0

matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 7.1
    env:
    - GET_COVERAGE=1
  allow_failures:
  - php: nightly

before_script:
- ./.travis/configure.sh
- travis_retry composer --no-interaction install

script:
- |
  CMD='composer --no-interaction run-script test --'
  if test $GET_COVERAGE -eq 1; then CMD="$CMD --coverage-clover coverage-clover.xml"; fi
  $CMD

after_script:
- ./.travis/after-success.sh
